CREATE DATABASE team;
USE team;

CREATE TABLE application (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    hash VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    major VARCHAR(255) NOT NULL,
    year SMALLINT NOT NULL,
    event VARCHAR(255) NOT NULL,
    departments VARCHAR(255),
    similar VARCHAR(255) NOT NULL,
    english SMALLINT NOT NULL,
    linkedin VARCHAR(255),
    github VARCHAR(255),
    website VARCHAR(255),
    description VARCHAR(255) NOT NULL,
    extra VARCHAR(255),
    confirmed SMALLINT NOT NULL DEFAULT 0,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP
);
